"""Add supplier_prices table

Revision ID: 0e358a02c7dd
Revises: 9d6aa527097a
Create Date: 2025-11-25 08:53:24.994869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e358a02c7dd'
down_revision: Union[str, Sequence[str], None] = '9d6aa527097a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('supplier_part_id', sa.String(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('available_qty', sa.Integer(), nullable=False),
    sa.Column('stock_status', sa.String(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('min_order_qty', sa.Integer(), nullable=True),
    sa.Column('pack_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_prices')
    # ### end Alembic commands ###
