"""Remove redundant columns from parts

Revision ID: 110812f61a30
Revises: 3267e85c7113
Create Date: 2025-11-27 10:51:42.634067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '110812f61a30'
down_revision: Union[str, Sequence[str], None] = '3267e85c7113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('parts_supplier_id_fkey'), 'parts', type_='foreignkey')
    op.drop_column('parts', 'supplier_part_id')
    op.drop_column('parts', 'supplier_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('parts', sa.Column('supplier_part_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('parts_supplier_id_fkey'), 'parts', 'suppliers', ['supplier_id'], ['id'])
    # ### end Alembic commands ###
