"""Make minor changes

Revision ID: 3267e85c7113
Revises: b6801ec22cff
Create Date: 2025-11-26 19:06:02.454933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3267e85c7113'
down_revision: Union[str, Sequence[str], None] = 'b6801ec22cff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventories')
    op.add_column('pricing_rules', sa.Column('rule_name', sa.String(), nullable=False))
    op.alter_column('pricing_rules', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pricing_rules', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pricing_rules', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('pricing_rules_name_key'), 'pricing_rules', type_='unique')
    op.create_unique_constraint(None, 'pricing_rules', ['rule_name'])
    op.drop_column('pricing_rules', 'name')
    op.add_column('shipping_rates', sa.Column('price_pln', sa.Numeric(precision=19, scale=4), nullable=False))
    op.drop_column('shipping_rates', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping_rates', sa.Column('price', sa.NUMERIC(precision=19, scale=4), autoincrement=False, nullable=False))
    op.drop_column('shipping_rates', 'price_pln')
    op.add_column('pricing_rules', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pricing_rules', type_='unique')
    op.create_unique_constraint(op.f('pricing_rules_name_key'), 'pricing_rules', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('pricing_rules', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pricing_rules', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pricing_rules', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('pricing_rules', 'rule_name')
    op.create_table('inventories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('part_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('available_qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stock_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('inventories_part_id_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('inventories_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('inventories_pkey'))
    )
    # ### end Alembic commands ###
