"""Update parts table

Revision ID: 7d5106efb669
Revises: a2cc281f8a1d
Create Date: 2025-11-26 18:53:46.677310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d5106efb669'
down_revision: Union[str, Sequence[str], None] = 'a2cc281f8a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('brand_id', sa.Integer(), nullable=False))
    op.add_column('parts', sa.Column('normalized_part_number', sa.String(), nullable=False))
    op.add_column('parts', sa.Column('description', sa.String(), nullable=False))
    op.create_foreign_key(None, 'parts', 'brands', ['brand_id'], ['id'])
    op.drop_column('parts', 'decription')
    op.drop_column('parts', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('parts', sa.Column('decription', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'parts', type_='foreignkey')
    op.drop_column('parts', 'description')
    op.drop_column('parts', 'normalized_part_number')
    op.drop_column('parts', 'brand_id')
    # ### end Alembic commands ###
