"""Add warehouses table

Revision ID: 8d2bf0dabe71
Revises: 04642aa14af6
Create Date: 2025-11-25 08:19:52.346737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2bf0dabe71'
down_revision: Union[str, Sequence[str], None] = '04642aa14af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('shipping_zone_id', sa.Integer(), nullable=False),
    sa.Column('default_lead_time_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shipping_zone_id'], ['shipping_zones.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouses')
    # ### end Alembic commands ###
