"""Add fx_rates table

Revision ID: 95a5fbd9bf61
Revises: 
Create Date: 2025-11-23 19:38:43.953718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95a5fbd9bf61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.CHAR(length=3), nullable=False),
    sa.Column('to_currency', sa.CHAR(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency', 'to_currency')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fx_rates')
    # ### end Alembic commands ###
