"""Add pricing_rules table

Revision ID: a2cc281f8a1d
Revises: 5f84cea90606
Create Date: 2025-11-25 09:02:45.412632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2cc281f8a1d'
down_revision: Union[str, Sequence[str], None] = '5f84cea90606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('price_min', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('price_max', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('warehouse_region', sa.String(), nullable=False),
    sa.Column('margin_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fixed_markup', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('rounding_rule', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricing_rules')
    # ### end Alembic commands ###
