"""Update supplier_prices table

Revision ID: b6801ec22cff
Revises: 7d5106efb669
Create Date: 2025-11-26 19:01:22.112596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6801ec22cff'
down_revision: Union[str, Sequence[str], None] = '7d5106efb669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_prices', sa.Column('supplier_sku', sa.String(), nullable=False))
    op.add_column('supplier_prices', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('supplier_prices', 'supplier_part_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_prices', sa.Column('supplier_part_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('supplier_prices', 'updated_at')
    op.drop_column('supplier_prices', 'supplier_sku')
    # ### end Alembic commands ###
