"""Add shipping_rates table

Revision ID: c603a05b258f
Revises: 11d4d4a2cdba
Create Date: 2025-11-24 08:27:34.490790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c603a05b258f'
down_revision: Union[str, Sequence[str], None] = '11d4d4a2cdba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipping_zone_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_region', sa.String(), nullable=False),
    sa.Column('weight_min', sa.Double(), nullable=False),
    sa.Column('weight_max', sa.Double(), nullable=False),
    sa.Column('price', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('carrier', sa.String(), nullable=False),
    sa.Column('service_level', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['shipping_zone_id'], ['shipping_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipping_rates')
    # ### end Alembic commands ###
